global:
  smtp_smarthost: 'localhost:587'
  smtp_from: 'alerts@ethiomarket.com'

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'web.hook'
  routes:
  - match:
      severity: critical
    receiver: 'critical-alerts'
  - match:
      severity: warning
    receiver: 'warning-alerts'

receivers:
- name: 'web.hook'
  webhook_configs:
  - url: 'http://localhost:5000/api/alerts/webhook'
    send_resolved: true

- name: 'critical-alerts'
  webhook_configs:
  - url: 'http://localhost:5000/api/alerts/webhook'
    send_resolved: true
    title: 'CRITICAL ALERT: {{ .GroupLabels.alertname }}'
    text: |
      {{ range .Alerts }}
      Alert: {{ .Annotations.summary }}
      Description: {{ .Annotations.description }}
      Alert (AM): {{ .Annotations.summary_am }}
      Description (AM): {{ .Annotations.description_am }}
      Severity: {{ .Labels.severity }}
      Service: {{ .Labels.service }}
      {{ end }}

- name: 'warning-alerts'
  webhook_configs:
  - url: 'http://localhost:5000/api/alerts/webhook'
    send_resolved: true
    title: 'WARNING: {{ .GroupLabels.alertname }}'
    text: |
      {{ range .Alerts }}
      Alert: {{ .Annotations.summary }}
      Description: {{ .Annotations.description }}
      Alert (AM): {{ .Annotations.summary_am }}
      Description (AM): {{ .Annotations.description_am }}
      Severity: {{ .Labels.severity }}
      Service: {{ .Labels.service }}
      {{ end }}

inhibit_rules:
- source_match:
    severity: 'critical'
  target_match:
    severity: 'warning'
  equal: ['alertname', 'dev', 'instance']